[globals]
DEBUG = 0
ENCODING = UTF-8
PREFIX = DICT.
UI = ../template/
; AUTOLOAD = ../src/
LOCALES = ../dict/
TEMP = ../var/temp/
LOGS = ../var/log/
UPLOADS = ../var/upload/
FALLBACK = en
ONERROR = 
CACHE = FALSE
PACKAGE =

[CONF.mail]
enable = 0
host = localhost
port = 25
user =
pass =
scheme =
defaultsender.email = noreply@localhost
defaultsender.name =
mime = text/html

[CONF.database]
enable = 0
engine = sql
type = mysql
user = root
pass =
data =
host = localhost
port = 3306
folder = ../database/jig/

[CONF.session]
; cache | sql | mongo | jig | empty for default php sessoin
engine = 
table = sessions
folder = ../var/sessions/
key = CSRF

[CONF.session.cookie]
options.lifetime = 
options.path = 
options.domain = 
options.secure = 
options.httponly = 
options.samesite = 

[CONF.sanitizer]
parse.enable = 1
sanitize.enable = 1
sanitize.variables = GET,POST,PUT
sanitize.exclude = password,password_verify

[CONF.security]
csrf.enable = 0
csrf.methods = POST,PUT
xss.enable = 0
xss.exclude = password,password_verify

[CONF.cookie]
options.lifetime = 31536000
options.path = /
options.domain = 
options.secure = false
options.httponly = true
options.samesite = Strict

[CONF.log]
file = log.txt

[CONF.jwt]
options.lifetime = 60
options.secret = 'öjhefwn/&()/&HIJFIOENFIOEN()*Zuio)(*'

[CONF.header]
contenttype = application/json
accesscontrolalloworigin = 
accesscontrolallowheaders = 
accesscontrolallowmethods = 
accesscontrolallowcredentials = 

[CONF.services]
frontend.url =

[routes]
[redirects]
[maps]
